### ISSUE TITLE
Introduction to Groovy

### ISSUE THREAD

**Issue by MikhailShumenko** [architecture-playground/jenkins-docker-compose#4]
- Create groovy-playground repository
- Learn base info about how to write groovy scripts
- Create a few groovy scripts: 
-- array processing (find max-min);
-- interact with GitHub REST API;
-- create few Groovy classes and use them in your scripts
-- import groovy libraries to project
-- groovy DSL
-- create "Hello World" Jenkins library and use it in our pipelines

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Learn groovy

**Comment by BulgakovAnton** [comment]
:clock1: 3h read about groovy

**Comment by BulgakovAnton** [comment]
:clock1: 8h taught groovy and sorted out libraries jenkins wrote the first script

**Comment by BulgakovAnton** [comment]
:clock1: 5h 30m
changed one Jenkins file using Jenkins libraries, And I began to deal with the operation of strings in Java

**Comment by BulgakovAnton** [comment]
:clock1: 8h 
studied Groovy libraries, modified the jenkins file and studied how to transfer data to a script

**Comment by BulgakovAnton** [comment]
:clock1: 7h 
Today I studied the groove syntax in scripts, passed the name as a parameter to the script.
P.S. again there is no light. And now the laptop will sit in the evening I will rewrite all the Jenkins files

**Comment by BulgakovAnton** [comment]
:clock1: 8h today i studied the groovy syntax and rewrite jenkinsfile, also start learn groovy closures.

**Comment by BulgakovAnton** [comment]
:clock1: 8h structured groovy-playground, and began to engage in Validate Commits

**Comment by MikhailShumenko** [comment]
Dedicated PR is opened at https://github.com/architecture-playground/groovy-playground/pull/1

**Comment by BulgakovAnton** [comment]
:clock1: 8h
Today I executed the command and wrote the output from the console to a file. Slightly delved into grooving methods

**Comment by BulgakovAnton** [comment]
:clock1: 6h
Today I cut the SCA commit and continued to deal with methods.

**Comment by BulgakovAnton** [comment]
:clock1: 5h 30m
studied patterns and regular expressions began to deal with patterns and connecting libraries

**Comment by BulgakovAnton** [comment]
:clock1: 8h
